version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [Refactor]
    target-branch: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels: [Refactor]
    target-branch: development
